name: research-paper-agent
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - api_data:/api_data
    networks:
      - research-paper-agent-network

  search:
    image: karust/openserp
    container_name: search
    restart: unless-stopped
    ports:
      - "7500:7000"
    command: serve -a 0.0.0.0 -p 7000
    networks:
      - research-paper-agent-network

volumes:
  api_data:

networks:
  research-paper-agent-network:
    driver: bridge