"""Email sending service."""

from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import aiosmtplib

from app.core.config import get_settings

settings = get_settings()


class EmailService:
    """Service for sending emails with attachments."""

    def __init__(self):
        self.smtp_host = None
        self.smtp_port = None
        self.smtp_username = None
        self.smtp_password = None
        self.from_email = None

    def configure(
        self, host: str, port: int, username: str, password: str, from_email: str
    ):
        """Configure SMTP settings."""
        self.smtp_host = host
        self.smtp_port = port
        self.smtp_username = username
        self.smtp_password = password
        self.from_email = from_email

    async def send_email(
        self,
        to_email: str,
        subject: str,
        html_content: str,
        attachments: list[dict] | None = None,
    ) -> bool:
        """Send an email with optional attachments."""
        if not all(
            [self.smtp_host, self.smtp_port, self.smtp_username, self.smtp_password]
        ):
            raise ValueError("Email service not configured")

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.from_email
        msg["To"] = to_email

        html_part = MIMEText(html_content, "html")
        msg.attach(html_part)

        if attachments:
            for attachment in attachments:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(attachment["content"])
                encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition",
                    f'attachment; filename="{attachment["filename"]}"',
                )
                msg.attach(part)

        try:
            await aiosmtplib.send(
                msg,
                hostname=self.smtp_host,
                port=self.smtp_port,
                username=self.smtp_username,
                password=self.smtp_password,
                use_tls=True,
            )
            return True
        except (aiosmtplib.SMTPException, OSError, TimeoutError) as e:
            print(f"Email sending failed: {e}")
            return False


email_service = EmailService()


async def send_research_email(
    to_email: str,
    topic: str,
    paper_content: dict,
    attachments: list[dict] | None = None,
) -> bool:
    """Send a research paper via email."""
    subject = f"Research Paper: {topic}"

    html_content = f"""
    <html>
    <body>
        <h1>Research Paper: {topic}</h1>
        <p>Your research paper has been generated successfully!</p>

        <h2>Abstract</h2>
        <p>{paper_content.get("abstract", "N/A")}</p>

        <h2>Key Sections</h2>
        <ul>
            <li>Introduction</li>
            <li>Literature Review</li>
            <li>Discussion</li>
            <li>Conclusion</li>
        </ul>

        <p>Please find the complete paper attached.</p>

        <hr>
        <p><small>Generated by Research Paper Agent</small></p>
    </body>
    </html>
    """

    return await email_service.send_email(to_email, subject, html_content, attachments)
